#!/usr/bin/env bash
set -euo pipefail

# Test suite for Knot Deskflow KVM Module & Client Runner (ISSUE-09 / ISSUE-10)
KNOT_ROOT="$(cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")/.." && pwd)"

echo "=== [Test 1] Bash Syntax Verification ==="
bash -n "$KNOT_ROOT/core/modules/deskflow.sh"
echo "  -> deskflow.sh syntax: OK"

echo "=== [Test 2] Deskflow Compiler Integration (deskflow_compile_server_config) ==="
TMP_TEST_DIR="$(mktemp -d)"
trap 'rm -rf "$TMP_TEST_DIR"' EXIT

export HOME="$TMP_TEST_DIR/home"
mkdir -p "$HOME/.config/Deskflow" "$HOME/.local/state/knot" "$HOME/.config/knot/swarms/testswarm/nodes"

# Setup test topology
cat << 'TOPO_EOF' > "$HOME/.config/knot/swarms/testswarm/topology.json"
{
  "anchor": "desktop",
  "screens": ["desktop", "laptop"],
  "layout": {
    "desktop": {
      "left": {
        "node": "laptop",
        "span": [60, 100]
      }
    }
  }
}
TOPO_EOF

cat << 'NODE1_EOF' > "$HOME/.config/knot/swarms/testswarm/nodes/desktop.json"
{
  "id": "desktop",
  "hostname": "test-anchor",
  "role": "anchor",
  "display": {"resolution": "2560x1440"}
}
NODE1_EOF

cat << 'NODE2_EOF' > "$HOME/.config/knot/swarms/testswarm/nodes/laptop.json"
{
  "id": "laptop",
  "hostname": "test-strand",
  "role": "strand",
  "display": {"resolution": "1920x1080"}
}
NODE2_EOF

# Set active swarm
echo "testswarm" > "$HOME/.local/state/knot/active_swarm"

# Source deskflow module
# Stub autounlock_configure and systemctl to avoid system modifications
autounlock_configure() { return 0; }
systemctl() { return 0; }
sudo() { "$@"; }

# Test deskflow_compile_server_config
source "$KNOT_ROOT/core/modules/deskflow.sh"

deskflow_compile_server_config "unlocked"
CONF_FILE="$HOME/.config/Deskflow/deskflow-server.conf"
if [ ! -f "$CONF_FILE" ]; then
  echo "Error: deskflow-server.conf not created!" >&2
  exit 1
fi

grep -q "test-anchor:" "$CONF_FILE"
grep -q "test-strand:" "$CONF_FILE"
grep -q "left(60,100) = test-strand(0,100)" "$CONF_FILE"
grep -q "right(0,100) = test-anchor(60,100)" "$CONF_FILE"
echo "  -> deskflow_compile_server_config generated correct reciprocal configuration: OK"

# Test locked mode
deskflow_compile_server_config "locked"
grep -q "test-anchor:" "$CONF_FILE"
anchor_links="$(awk '/test-anchor:/{flag=1; next} /^[[:space:]]*[a-zA-Z0-9_-]+:/{flag=0} flag && /=/{print}' "$CONF_FILE")"
if [ -n "$anchor_links" ]; then
  echo "Error: locked mode did not omit anchor outbound links: $anchor_links" >&2
  exit 1
fi
echo "  -> deskflow_compile_server_config locked mode confines cursor: OK"

# Test backward compatible deskflow_write_server_conf
deskflow_write_server_conf "unlocked"
grep -q "left(60,100) = test-strand(0,100)" "$CONF_FILE"
echo "  -> deskflow_write_server_conf alias: OK"

echo "=== [Test 3] Deskflow Client Runner Lifecycle ==="
CLIENT_RUNNER="$TMP_TEST_DIR/bin/knot-deskflow-client"
mkdir -p "$(dirname "$CLIENT_RUNNER")"

# Extract client runner script from deskflow.sh deploy section
sed -n '/RUNNER_EOF'\''/,/RUNNER_EOF/p' "$KNOT_ROOT/core/modules/deskflow.sh" | sed '1d;$d' > "$CLIENT_RUNNER"
chmod +x "$CLIENT_RUNNER"
bash -n "$CLIENT_RUNNER"
echo "  -> client runner script syntax: OK"

# 3a. Standalone mode (active_swarm=none)
echo "none" > "$HOME/.local/state/knot/active_swarm"
# Provide fake knot CLI
export PATH="$TMP_TEST_DIR/bin:$PATH"
cat << 'KNOT_EOF' > "$TMP_TEST_DIR/bin/knot"
#!/usr/bin/env bash
exit 0
KNOT_EOF
chmod +x "$TMP_TEST_DIR/bin/knot"

STANDALONE_OUT="$("$CLIENT_RUNNER")"
if ! echo "$STANDALONE_OUT" | grep -q "Active swarm is none"; then
  echo "Error: Expected graceful standalone exit, got: $STANDALONE_OUT" >&2
  exit 1
fi
echo "  -> Standalone mode clean exit: OK"

# 3b. Stop action
STOP_OUT="$("$CLIENT_RUNNER" stop)"
echo "  -> Client runner stop action: OK"

# 3c. Connected mode resolution
echo "testswarm" > "$HOME/.local/state/knot/active_swarm"
cat << 'SWARM_EOF' > "$HOME/.config/knot/swarms/testswarm/swarm.conf"
ANCHOR_ID="desktop"
ANCHOR_HOST="test-anchor"
SWARM_NAME="Test Swarm"
SWARM_EOF

# Provide mock knot resolve
cat << 'RESOLVE_EOF' > "$TMP_TEST_DIR/bin/knot"
#!/usr/bin/env bash
if [ "$1" = "resolve" ]; then
  echo "10.0.0.42"
  exit 0
fi
exit 1
RESOLVE_EOF
chmod +x "$TMP_TEST_DIR/bin/knot"

# Mock deskflow-core to verify invocation and config
cat << 'DF_EOF' > "$TMP_TEST_DIR/bin/deskflow-core"
#!/usr/bin/env bash
echo "deskflow-core invoked with: $*"
exit 0
DF_EOF
chmod +x "$TMP_TEST_DIR/bin/deskflow-core"

CLIENT_EXEC_OUT="$("$CLIENT_RUNNER")"
CLIENT_CONF="$HOME/.config/Deskflow/Deskflow.conf"
if [ ! -f "$CLIENT_CONF" ]; then
  echo "Error: Deskflow.conf not generated by client runner!" >&2
  exit 1
fi

grep -q "remoteHost=10.0.0.42" "$CLIENT_CONF"
echo "  -> Dynamic Anchor target resolution and config generation: OK"
echo "  -> Client exec invocation: OK"

echo "=== [✓] ALL DESKFLOW COMPILER & CLIENT RUNNER TESTS PASSED! ==="
